version: '3.8'

services:
  catalog.api:
    container_name: lde.product.api  
    build:
      context: .
      dockerfile: Product/Product.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5001
    ports:
      - 5001:5000
  catalog2.api:
    container_name: lde.catolog.api  
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5002
    ports:
      - 5002:5000
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4


 